name: Eleventy Build
on: [push]

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --output _dist
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_dist
          github_token: ${{ secrets.GITHUB_TOKEN }}